language: python
os: linux
dist: xenial
python: 3.7

env:
  global:
    # Doctr deploy key for pcdshub/lcls-twincat-motion-example
    - secure: "qFE0NMNbEjr7lLngQgUM5chkTt3gk2PqoY9meyW+w9/GwoSr0/d8TOMDGZmheXBJhd2FBc7a/KRejBHR6Wzt8sNei5d/ifvRM2WccbpSWF+ernrPnGW8tcK3Hn3er3v0nnjfws3G1t4nLdFcg32FAEkM3/vMPO21ZXHVtm2jYrg0KdTa6SrBz1U7Ex89x5R7vySotHWCIWbVU9cc0DREzboQx3vXnYsCZcw4skASTyOSvTARNrIB8YjTVnKIiVg35GwWhmvTLzAwDnnCMy6ifHoxG4T+j7aXtE1qBdcRnTyuUnPxdstQSc6zJ9f+53W1PUu1SpwssFawQQHsPpeiKsv6Lp3pOwugdNItICdKOULyzK8vh7YavIpAtug6qebt6DzTU44hGAdpCKUpBIaqMH+AnFTAm6Qxzw8YiYCSrWTZPBxaismc0Gu4H0v1WDXGHjj9v43OsyVLXinGgroq5YfR8Edb0PMq48mNI1nMgjZfOW1ih6vk8IrrbXKixkStctRkOfMiKXvznM/wHQ8Vqwh0WViUOJkPCvUHyXPqZozqAXXVTzGCkNYx8RUkB3DUFO/o9IsgqThj+n2B92JslN6LNErGQYFF5KBIObR1x+jhN2KwWULJXGI5BI77OKj2WDRJBau7cwL5mBeoNRfbKOw8aqlmUcy+62AQDHvYCSU="

jobs:
  include:
    - name: Project summary
      env: TWINCAT_SUMMARY=1
    - name: Pragma linting
      env: TWINCAT_PRAGMALINT=1
    - name: Documentation building
      env: TWINCAT_BUILD_DOCS=1
    - name: Twincat Style
      env: TWINCAT_STYLE=1
    - name: Pre-commit Checks
      env: PRE_COMMIT=1

install:
  # Import the helper scripts
  - git clone --depth 1 git://github.com/pcdshub/pcds-ci-helpers.git
  # Start the helper-script initialization + run based on environment variables
  - source pcds-ci-helpers/travis/init.sh
